### ISSUE TITLE
Use python 3 as primary interpreter

### ISSUE THREAD

**Issue by benabel** [lebigot/uncertainties#110]
Python 2.7 will not be maintained past 2020. It's time for the package to turn code into python3 code and maybe propose python2 code via [pasteurize](http://python-future.org/pasteurize.html).

**Comment by benabel** [comment]
@lebigot I'm currently working on code changes to turn code into python3 first. I currently can pass the tests for python 3.8 and python 2.7. Are you interested in these changes? If yes which python versions ranges you would like to support?

**Comment by lebigot** [comment]
Now is a good time to switch so yes, I think that a Python 3 main version is now best.

Python 2.7 is still out there in the wild, and will remain for some time (despite its lack of maintenance), so I want to keep a working 2.7 version. Any Python version before 2.7 is a bonus (for the rare users who for some reason might be stuck with a version from before 2010).

As for the Python 3 branch, I guess that supporting Python 3.5+ seems reasonable? Anything before that is a bonus.

I did leave some notes in the code where some less obvious changes could use Python 2.7+ features. They are marked with "!!" and contain "Python" in the comment, if I remember correctly.

I would welcome any pull request.

**Comment by BishopWolf** [comment]
You can also make a fixed wheel for python 2.7 and move from there and support only updates for python3. python2 will not accept further fixes so why would you provide fixes for that? (unless critical).

**Comment by lebigot** [comment]
I intend to keep supporting Python 2.7 users of `uncertainties` even if Python 2.7 itself is not supported anymore simply because some users still use it.

**Comment by BishopWolf** [comment]
> I intend to keep supporting Python 2.7 users of `uncertainties` even if Python 2.7 itself is not supported anymore simply because some users still use it.

You can easily do this by making use of the package `six`, it is very straightforward and very easy to use.

**Comment by CAM-Gerlach** [comment]
Just FYI, `future` is strongly recommended over the legacy `six` by essentially all the current porting guides, including the [official one in the Python docs](https://docs.python.org/3/howto/pyporting.html), for modern dual-stack ports, as it is a near superset of the latter's functionality while being more capable, more robust, easier to use, and resulting in cleaner, easier to maintain and more future-proof code (no pun intended :)

**Comment by benabel** [comment]
#111 already use `future`, and is tested with both in `python2.7` and `python3`.

**Comment by CAM-Gerlach** [comment]
Right, your code follows basically every best practice I can think of, and probably some I can't. I was replying to @BishopWolf 's comment. You might want to see #116 for some relevant discussion there about #111 mostly thanks to me going way off topic over there. If we can move those comments to #111 that would be great if @lebigot agrees.

**Comment by benabel** [comment]
I see #111 as a starting point for this modernization, with a good testing environment. When(If) merged, it would be possible to enhance the code in a python3 way, and add propositions from #116, #52 and others.

**Comment by lebigot** [comment]
Python 3 is now the main interpreter.

The new version requires Python 2.7+ (2.6 would be doable, but this would involve downgrading dictionary comprehensions, for instance).

Like @CAM-Gerlach, I also understand that future is being recommended over six, so that's what I used. The code doesn't look much more modern to me (as it was already using the more efficient `.iteritems()` and such). In particular, we still have some `basestring` here and there, some `u'…'` literals, and classes that inherit from `object`. I am hoping that some of the filters of `futurize` can automatically clean this up when support for Python 2 is dropped.

@benabel: I tried to use your pull request https://github.com/lebigot/uncertainties/pull/111 but it contains so many intermingled changes (1000 lines modified) on so many different subjects (single source for Python 2 and 3, new setup.py, flake8, Cox…), and also (probably automatic) changes that are either suboptimal or that I don't agree with, that the best I can do is to get _inspired_ by it. In the first place, this motivated me to release the current single Python 2+3 source. The same is true for wheels.

I will also probably implement some other interesting things that Pull Request https://github.com/lebigot/uncertainties/pull/111 does (and get some inspiration from it):
- Move from nose to pytest
- Tests with tox
- Lint and tests through GitHub Actions
- … and maybe more?

**Comment by lebigot** [comment]
PS: if someone has an opinion on whether Python 2 should better be supported through [pasteurize](http://python-future.org/pasteurize.html), let me know! This would make the code more modern, but I am afraid that some packages might need universal wheels (which would become impossible).
