### ISSUE TITLE
weird combination of uncertainties

### ISSUE THREAD

**Issue by denfromufa** [lebigot/uncertainties#39]
can you please review this gist https://gist.github.com/denfromufa/d88f54b0d3e80579d3f1:

```
e1=5.
e2=20.
q1=ufloat(80.,e1)
q2=ufloat(80.,e2)
qharm=(q1/e1+q2/e2)/(1/e1+1/e2)
qharm # 80.0+/-5.656854249492381
qharm.error_components() # {80.0+/-5.0: 4.0, 80.0+/-20.0: 4.0}
```

why are error components same if the original errors are different and the resulting expression is symmetric?

**Comment by lebigot** [comment]
Because you rescale `q1` and `q2` in `qharm`, so the errors are rescaled. Concretely, if you simply look at `q1/e1` and `q2/e2` you can see that they have the same error (±1).

Again, you really need to learn more about error propagation theory (as I was advising in your previous open issue): this question and the previous one you asked would be better asked in other places on the net (maybe http://math.stackexchange.com, etc.).

**Comment by denfromufa** [comment]
@lebigot thanks for your explanation, now it makes sense!
