### ISSUE TITLE
Provide upper and lower bounds as array

### ISSUE THREAD

**Issue by icymist** [lebigot/uncertainties#48]
We currently have:

```
In [1]: from uncertainties import ufloat
In [2]: x = ufloat(10, 0.5)
In [3]: x.nominal_value
Out[3]: 10.0
In [4]: x.std_dev
Out[4]: 0.5
```

Would it be a good idea to have something along the lines of:
```
In [5]: x.bounds
Out[5]: (9.5, 10.5)
```

**Comment by lebigot** [comment]
I prefer not to do this, because these "bound" values are really not bounds: in this module, 10±0.5 represents a probability distribution "centered" around 10 (10 could be the median, for instance), with a _standard deviation_ of 0.5. Thus, numbers with uncertainties are generally _not_ bounded in any way.
