### ISSUE TITLE
Plans for native Python 3 suport and dropping support for older Python versions

### ISSUE THREAD

**Issue by rth** [lebigot/uncertainties#56]
Currently `Uncertainties` supports python 2.4-2.7 with support of python 3.2-3.3 through `2to3` converter. There is also the Python 2.3 branch that appears to be still periodically synced.
![untitled](https://cloud.githubusercontent.com/assets/630936/18231140/a5d823c6-72b0-11e6-9c4c-dd4d564c1a20.png)

The support of such outdated python versions (e.g. python 2.3 was installed in Ubuntu Hardy LTS released in 2008 which reached end of life in 2013) is fairly unconventional in the scientific python community were currently most packages support 2.6-2.7 and natively 3.2-3.5 (i.e. without using 2to3), cf. for instance the [last numpy release](https://docs.scipy.org/doc/numpy/release.html) which is also an optional dependency. Also see  the [Python 3 statement](https://python3statement.github.io/) for the dropping of support for PY2 in major scientific python packages by 2020. 

The ongoing support for outdated python versions 2.4-2.5, 2.3 and to a lesser extent 2.6, and the lack of a native 3.2+ support, prevents from using the last features and optimizations of the language  (also related to issue #52) and  in my opinion might also dissuade new contributors who might have already switched to PY3. 

Is there any plans to add native Python 3.2-3.5 support and drop support for older Python versions in the future releases? I would be happy to work on this.

**Comment by lebigot** [comment]
Interesting question.

Thank you for suggesting to work on the native 3.2–3.5 support.

While I do appreciate Python 3 compared to Python 2, my plan is to progressively move to higher and higher versions of Python when I feel that the code becomes too suboptimal or less legible. This is what happened a month ago when I switched the main version to Python 2.7 (instead of Python 2.6)—with older versions supported through an ad hoc branch (master_python2.3), and more recent versions supported with 2to3.

I would guess that it is better if I do the conversion myself, as I know the code well enough to have many of the ideas that could make it more adapted to Python 3. If the main version becomes Python 3 through external help, I am not sure that I will be able to easily track obvious areas where the code could be updated (because 2to3 highlights these areas for me, and it could not be used as easily anymore).

Also, in the past, I have often encountered obsolete Python installations in computing clusters or isolated machines used by larger scientific collaborations. Staying with Python 2 as the native version makes adapting the code to these older version easier—thereby increasing the chances that I don't shut some people out.

The nature of this package, its limited number of external contributions, and the fact that Python 2 and 3 are close enough make me think that not too many people would refrain from contributing while Python 2 is the native version.

For these reasons, I do not see the need yet to move to Python 3 for the native version.

But it is clearly coming.

**Comment by rth** [comment]
Thanks for your response! I understand  the challenges of maintaining python packages over years with an existing user base. 

I didn't mean to fully move to Python 3 for the native version. If the current main version is Python 2.7, it should require only very minor changes to make it work with Python 3 as it is, without the need to 2to3, using,
  -  Some `from __future__ import` (which is already used for division I think),

        from __future__ import absolute_import
        from __future__ import division
        from __future__ import print_function
  - and a few calls to the  [`six` compatibility library](https://pythonhosted.org/six/)

The list of [Py2/3  compatible idioms](http://python-future.org/compatible_idioms.html) might also be useful.

But in any case I understand that  you would want to do the conversion yourself, when the time is right. Thanks again for the detailed response!

**Comment by lebigot** [comment]
Now I see what you mean, thank you for making this clear.

I must say that I like the current setup, because `2to3` is part of standard Python, whereas `six` is not.
