### ISSUE TITLE
converter not working with python3

### ISSUE THREAD

**Issue by atsteich** [lebigot/uncertainties#67]
Loading data with uncertainties in the way descriped in https://pythonhosted.org/uncertainties/numpy_guide.html
does only work for pyhton 2.7, not for 3.0. Loading data in that way leads to:
TypeError: cannot use a string pattern on a bytes-like object
Possible Reason may be that in Python 3 strings are unicode by default, whereas in Python 2 strings are bytes by default.

**Comment by lebigot** [comment]
Indeed, thanks. The reason is that in Python 3, NumPy's `loadtxt()` reads _bytestrings_ from the file (instead of strings)—this is hinted at in `loadtxt()`'s docstring.

I added the solution in the documentation you point to: https://pythonhosted.org/uncertainties/numpy_guide.html#storing-arrays-in-text-format.

Now, in a better world, both `numpy.savetxt()` and `numpy.loadtxt()` would _require an encoding_ and the converters would work on strings, so that everything is clean… This is a known problem: https://github.com/numpy/numpy/issues/4543.
