### ISSUE TITLE
[Wish] port this library for R

### ISSUE THREAD

**Issue by ericoporto** [lebigot/uncertainties#85]

**Comment by moorepants** [comment]
Maybe try something like: https://blog.rstudio.com/2018/03/26/reticulate-r-interface-to-python/

**Comment by lebigot** [comment]
I'd be happy to discuss the logic behind transparent uncertainty calculations in `uncertainties` with anyone interested in this subject.

However, since I do not plan at all to go back to R, I'll leave this "issue" open for some time so that people can comment on it some, but I will then close it, as it cannot be resolved as part of this Python project.

**Comment by lebigot** [comment]
This is an issue for R users/programmers, which precludes me from working on it (both now and in the foreseeable future). Mentioning it in R forums would be useful.
