### ISSUE TITLE
TypeError in uncertainties.unumpy with Numpy dev version

### ISSUE THREAD

**Issue by cdeil** [lebigot/uncertainties#89]
Since recently, with the Numpy development version, we are seeing this error:

```
>   pinv_default = numpy.linalg.pinv.__defaults__[0]  # Python 1, 2.6+:
E   TypeError: 'NoneType' object is not subscriptable
/home/travis/miniconda/envs/test/lib/python3.6/site-packages/uncertainties/unumpy/core.py:535: TypeError
```

https://travis-ci.org/gammapy/gammapy/jobs/443608528#L4364

@lebigot - Does it make sense to you? Can you reproduce?

If needed, I could try to extract a minimal test case.

**Comment by lebigot** [comment]
This does make sense: the source line you quote does not make any provision for the possible `None` value for `__defaults__`, whereas it should (https://docs.python.org/3/reference/datamodel.html). I am guessing that the fix should be simple, but I haven't looked at the details.

**Comment by lebigot** [comment]
I started looking in more details into this issue.

Can you check if you observe the _exact same_ problem? The message above indicates that the development version of NumPy removed (non-keyword-only) the default value for `rcond`, which should break many codes—so it's normal that `uncertainties` break too.

Now, the offending line from `uncertainties` certainly does not handle multiple versions of NumPy: the uncertainty-aware `pinv()` should accept arguments independently of the version of NumPy (there is an [additional argument](https://github.com/numpy/numpy/blob/62433284d65a3629a199958da2df3a807c60fab4/numpy/linalg/linalg.py#L1885) in NumPy 1.17), so it would be good to make this part of the code more general.

**Comment by toddrme2178** [comment]
I am getting the exact same error.  Running numpy 1.17.0 final from pypi.

**Comment by lebigot** [comment]
Thanks for the update. I am guessing that this comes from the additional argument added in NumPy 1.17.

This needs to be fixed ASAP.

The relevant code is probably all in the section starting at https://github.com/lebigot/uncertainties/blob/fa25b78559811af6cb580a7773cb857b75f3be46/uncertainties/unumpy/core.py#L485 (L485–L553). Any help would be welcome!

**Comment by paulromano** [comment]
It looks like this actually has to do with the `array_function_dispatch` decorator that is applied to functions in `numpy.linalg`. In numpy < 1.17, the decorator was effectively a no-op and just returned the original function, so looking at `__defaults__` worked. However, in numpy 1.17, a wrapper is returned and the wrapper itself doesn't have any argument defaults, hence why you get `None` for `__defaults__`. To get at the original function you could do something like `np.linalg.pinv.__wrapped__`, so the following should fix the issue in principle:
```Python
try:
    pinv_default = numpy.linalg.pinv.__defaults__[0]
except TypeError:
    pinv_default = numpy.linalg.pinv.__wrapped__.__defaults__[0]
```
I'd be happy to submit a PR with such a fix -- however, it doesn't address the extra `hermitian` argument in numpy 1.17 which would be a bigger change.

Also, for anyone (like me) who's finding that their CI jobs are failing because of this, a quick workaround is to set the environment variable `NUMPY_EXPERIMENTAL_ARRAY_FUNCTION=0` which will revert numpy to its pre-1.17 behavior.

**Comment by lebigot** [comment]
Thank you. I am planning to have a look this weekend: I consider that this is an urgent issue (both the change with `__defaults__` and the new argument).

**Comment by lebigot** [comment]
In the final fix, the code may want to use `inspect.signature().parameters` (for Python 3.3+).

**Comment by lebigot** [comment]
I incorporated Paul's fix in 6834ef6b433b209e2d7f52b375aa6412380acf08.

I still have to release it on PyPI.

The issue with the additional pinv() argument remains, but it is less pressing.

**Comment by lebigot** [comment]
The fix is now on PyPI (version 3.1.2).

**Comment by paulromano** [comment]
> In the final fix, the code may want to use `inspect.signature().parameters` (for Python 3.3+).

Agreed, that would make it a lot cleaner than checking `__defaults__`.

**Comment by lebigot** [comment]
This is what I ended up doing in 3.1.2.

**Comment by cdeil** [comment]
@lebigot and @paulromano - Thank you!
