### ISSUE TITLE
Calculate wrong expected (nominal value) for squared variables

### ISSUE THREAD

**Issue by perlpit** [lebigot/uncertainties#94]
It seems that when a ufloat variable is squared the calculated nominal value is wrong. 
The code:

x = ufloat(12, 5)
squared = x ** 2
print(squared.nominal_value)

Prints the value 144.0, which is incorrect. 
The correct value should be 169.0 from the formula:
E(X^2) = E(X) + V(X) = 12^2 + 5^2 = 144 + 25 = 169

It seems that the term with the variance of x (V(X)) is omitted in the calculations.  

Note:
If x = ufloat(12, 5) and y = ufloat(12, 5) then nominal value for x * y should be 144.0

**Comment by lebigot** [comment]
The `uncertainties` package [performs linear approximations](https://uncertainties-python-package.readthedocs.io/en/latest/tech_guide.html#linear-propagation-of-uncertainties) for propagating uncertainties, and the result that you observed is correct within this official framework.

Obtaining meaningful results thus imply that uncertainties be "small": in the case that you quote, this requires that x → x**2 be close to a straight line over 12±5, which is not at all the case.

Furthermore, the nominal value is defined as being representative of some reasonable "center" of the distribution, and _not_ necessarily its expected value (the [documentation](https://uncertainties-python-package.readthedocs.io/en/latest/tech_guide.html#mathematical-definition-of-numbers-with-uncertainties) indicates this as well). The reason is that only an exact calculation can guarantee an interpretation of the nominal value as the expected value, and this is in general a much slower calculation.

Thus, to summarize, the nominal value of `uncertainties` is simply a value where the real probability distribution is quite large, and is in the case of small uncertainties a good estimate of the mode/expected value/median of the real distribution.

Finally, if you are looking for more precise or exact calculations, [the documentation lists other packages](https://uncertainties-python-package.readthedocs.io/en/latest/tech_guide.html#constraints-on-the-uncertainties) that can do this (at the cost of much slower calculations, but this may be fine for just a few numbers).

I hope that this helps.
